### ISSUE TITLE
UAC handing issues - uncaught Win32Exception 0x80004005

### ISSUE THREAD

**Issue by draeath** [godarklight/DarkMultiPlayer#242]
It would be nice if whatever makes UAC escalation necessary for the http server to be optional. It's annoying to work with DMP on a normally headless server without turning UAC off.

I only see one reason for needing it, and it's punching holes through the firewall - something an administrator can do themselves (or perhaps the firewall isn't even enabled!) - unless of course they have chosen a port in the well-known range.

As well, if the user should abort the UAC prompt DMP crashes hard, instead of handling it gracefully (eg, not opening the firewall if that's what is happening) or even shut down properly. As of v0.1.6.1 the following is logged:
```
[04:37:54][INFO] : Starting HTTP server...
[04:37:54][DEBUG] : HTTP Server: access denied.
[04:37:54][DEBUG] : Prompting user to switch to administrator mode.
[04:38:00][FATAL] : Error in main server thread, Exception: System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at DarkMultiPlayerServer.Server.StartHTTPServer()
   at DarkMultiPlayerServer.Server.Main()
```

Shortly after, it crashes hard. Here's what's visible in the Windows logs when this occurs:
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2014-11-03T04:38:00.000000000Z" /> 
  <EventRecordID>25375</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>epicenter</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: DMPServer.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ComponentModel.Win32Exception Stack: at DarkMultiPlayerServer.Server.Main()</Data> 
  </EventData>
  </Event>
```
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2014-11-03T04:38:01.000000000Z" /> 
  <EventRecordID>25376</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>epicenter</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>DMPServer.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5454970f</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.3.9600.17278</Data> 
  <Data>53eebf2e</Data> 
  <Data>e0434352</Data> 
  <Data>000000000000606c</Data> 
  <Data>1b20</Data> 
  <Data>01cff71feed6008a</Data> 
  <Data>C:\games\KSP_DMPServer-release\DMPServer.exe</Data> 
  <Data>C:\WINDOWS\system32\KERNELBASE.dll</Data> 
  <Data>30ddda3b-6313-11e4-bed5-74d435856604</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by godarklight** [comment]
Mostly not needed anymore, so I'll close this. Supporting WinXP isn't that great a concern and the server list now has its own plugin and no longer needs the HTTP server.
